// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MeetupFilterInput struct {
	Name *string `json:"name"`
}

type NewMeetupInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type UpdateMeetupInput struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}
